### ISSUE TITLE
Add tools for PSF calculations

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/radio-beam#101]
@rgalvanmadrid has made the following tool to calculate the ratio of the dirty beam volume to the clean beam volume:

https://github.com/ALMA-IMF/reduction/commit/9d3846ff08e80a8c1fe1771d4ff87c3c628ead78#diff-91c493e486904d56f624b0744a0257ec2603050401cdb71aaa9d535316ecc8adR15-R88

I think that should live in `radio_beam` under a new `psf_tools.py` file, say?  @e-koch , any ideas on where this should live?

**Comment by e-koch** [comment]
It may be better as a utility function in spectral-cube to avoid a circular dependency in radio-beam (assuming we need to open the cube as a spectral-cube).

Do we have clean specific utilities stashed somewhere already? I don' think so. At the risk of adding too many packages to maintain, a separate lightweight clean utility package could be useful.

**Comment by keflavich** [comment]
Hm, I agree, actually.

I think we need a new repository for this.  What do we call it?

**Comment by keflavich** [comment]
https://github.com/ALMA-IMF/reduction/blob/master/misc/beam_volume_tools.py

**Comment by rgalvanmadrid** [comment]
Let me know if I need to modify anything or add checks, etc.

**Comment by keflavich** [comment]
OK thanks, we will probably ask for your help.  We have to figure out where to put it first, then we'll ask you to make a pull request there.

**Comment by e-koch** [comment]
To go into https://github.com/radio-astro-tools/beam-volume-tools
