### ISSUE TITLE
Time for a new release on PyPi?

### ISSUE THREAD

**Issue by smaret** [radio-astro-tools/radio-beam#111]
The tests for the current version of `radio-beam` (0.33) are broken:

```py
radio_beam/conftest.py:27: in <module>
    from astropy.tests.plugins.display import PYTEST_HEADER_MODULES, TESTED_VERSIONS
E   ModuleNotFoundError: No module named 'astropy.tests.plugins'
```

I think this is fixed on `master`.

Could you please make a new release on PyPi ?

**Comment by keflavich** [comment]
Yes, it's time for that.

@e-koch @astrofrog I pushed a changelog update to v0.3.4.  But... where do we specify our version?  `python setup.py sdist` got me version 0.0.0...

**Comment by astrofrog** [comment]
I think I know, will reply soon!

**Comment by smaret** [comment]
Thanks for the release.
