### ISSUE TITLE
push latest version into conda and pip

### ISSUE THREAD

**Issue by jpinedaf** [radio-astro-tools/radio-beam#120]
Hi,

I created a conda new environment for python 3.11 and installed the `radio-beam` package using `conda install radio-beam`. The problem is that it only got version 0.3.4, which did not work well with `astropy=6.0`. The same occurred with pip, which could only find version 0.3.4.

I did a git clone and performed the local installation, and everything seems to work. It would be great if the latest version is also reachable via pip and/or conda :-)

**Comment by e-koch** [comment]
Thank @jpinedaf. I'll push a new release to Pypi shortly.

**Comment by e-koch** [comment]
@jpinedaf v0.3.7 is now on pypi!
