### ISSUE TITLE
Support for beam tables from CASA

### ISSUE THREAD

**Issue by e-koch** [radio-astro-tools/radio-beam#30]
For wide-band cubes. I'm unsure if this is doable from FITS headers.

**Comment by keflavich** [comment]
Support for beam tables is now in spectral-cube, but not so much here.  We have a function to create an *average beam* from a beam table, but no means of handling beam arrays yet.

**Comment by keflavich** [comment]
https://github.com/radio-astro-tools/spectral-cube/issues/436 is related: a `Beams` object should support masking...

**Comment by e-koch** [comment]
Also noted in #51, which I'm very guilty of abandoning.

**Comment by e-koch** [comment]
Finsished #51
