### ISSUE TITLE
Release 0.3.2 (on pypi)?

### ISSUE THREAD

**Issue by olebole** [radio-astro-tools/radio-beam#79]
Hi,

there is a 0.3.1 release on Pypi, but a 0.3.2 tag on Github. The 0.3.1 is not compliant with astropy 4 (`astropy.extern.six`). It may be worth to put the 0.3.2 to Pypi as well.
For the Debian package, I get the versions from Pypi, that's why I rely a bit on this (but I can change if needed).

**Comment by keflavich** [comment]
I see 0.3.2 on pypi:
https://pypi.org/project/radio_beam/0.3.2/

Am I missing something?

**Comment by olebole** [comment]
Oh yes, my fault. My search script was buggy (`-` instead of `_`). Sorry for the confusion.
