### ISSUE TITLE
travis failures: pytest-astropy, flakes

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/radio-beam#85]
travis configuration requires fixes for these:

 * [ ] https://travis-ci.org/github/radio-astro-tools/radio-beam/jobs/688437469
 * [ ] https://travis-ci.org/github/radio-astro-tools/radio-beam/jobs/688437470

first says we need to install pytest-astropy.  Second says that `$FLAKES_OPT` is undefined.  Probably just means we need a test infrastructure overhaul

**Comment by e-koch** [comment]
Recommend we address these with the infrastructure updates in #82 (which needs to picked back up)

**Comment by e-koch** [comment]
Fixed in #82
